version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rpi-shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "50432:5432"

  web:
    build: .
    command: sh -c '../startup.sh'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DB_NAME=rpi-shop
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
volumes:
  data: